spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    hikari:
      schema: grpc
  flyway:
    default-schema: grpc
    create-schemas: true
grpc:
  server:
    security:
      enabled: true
      certificate-chain: classpath:certificates/server.crt
      private-key: classpath:certificates/server.key
      client-auth: optional
